name: environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - pip:
    - pandas
    - matplotlib
  #  - jupyterlab
    - zip
  #  - nbconvert
  #  - widgetsnbextension
  #  - ipykernel
  #  - ipywidgets
  #  - ipyleaflet
